# Introduction to Data Science 2026

# Week 1

## Exercise 1 | Matrix warm-up
<span style="background-color: #ccfff2"> *Note: You can find tutorials for NumPy and Pandas under 'Useful tutorials' in the course material.*</span>

One of the most useful properties of any scientific programming language (Python with NumPy, R, Julia, etc) is that they allow us to work with matrices efficiently. Let's learn more about these features!

### 1.1 Basics

1. Let's start by creating two arrays <span style="background-color: #ccfff2"> A</span> and <span style="background-color: #ccfff2"> B</span> which each have the integers <span style="background-color: #ccfff2"> 0, 1, 2, ..., 1e7-1</span>. Use the normal arrays or lists of the programming language you are using, e.g. *list* or *[ ]* or *numpy.array()* in Python.

In [1]:
# Use this cell for your code
import numpy as np

A = np.arange(int(1e7))
B = np.arange(int(1e7))

2. Create a function that uses a <span style="background-color: #ccfff2"> for loop</span> or equivalent to return a new array <span style="background-color: #ccfff2"> C</span>, which contains the <span style="background-color: #ccfff2"> element-wise sum of *A* and *B*</span>, e.g. C should contain the integers <span style="background-color: #ccfff2"> 0, 2, 4, etc</span>.

In [2]:
def add_with_for(A,B):
    C = []
    # add your code here
    for i in range(len(A)):
        C.append(A[i] + B[i])
    return C

3. Next, let's create another function that uses NumPy (or equivalent) to do the same. To try it out, allocate two arrays (e.g. using <span style="background-color: #ccfff2"> np.array</span> in NumPy) and add the arrays together using your function. Don't use loops, instead, find out how to add the two arrays directly. What do you notice in comparison to the previous function?

In [3]:
# Use this cell for your code
def add_with_numpy(A, B):
    return A + B

In [4]:
import time

# Using the time function, we can compare the speed of the two functions. The for-loop will be significantly slower than the numpy implementation.

t0 = time.time()
add_with_for(A, B)
print("for-loop time:", time.time() - t0)

t0 = time.time()
add_with_numpy(A, B)
print("numpy time:", time.time() - t0)

for-loop time: 3.928370952606201
numpy time: 0.052155256271362305

Thus, we can conclude using the Array implementation over the List implementation in Python is much more efficient.

### 1.2 Array manipulation

<span style="background-color: #ccfff2"> *Note: for the following exercises, only use NumPy or equivalent functions. Don't use any loops.* </span>
1. Create the following array:

*[hint: <span style="background-color: #ccfff2"> np.reshape</span>]*

In [5]:
# array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
#        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
#        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
#        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
#        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
#        [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
#        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
#        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
#        [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
#        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [6]:
# Use this cell for your code
np.arange(100).reshape(10, 10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

2. Create the following array:

In [7]:
# array([[0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.]])

In [8]:
# Use this cell for your code
row = np.arange(10.0) % 2
np.tile(row, (10, 1))

array([[0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.]])

3. Create the following array (D):

In [9]:
# array([[0., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
#        [1., 0., 1., 1., 1., 1., 1., 1., 1., 1.],
#        [1., 1., 0., 1., 1., 1., 1., 1., 1., 1.],
#        [1., 1., 1., 0., 1., 1., 1., 1., 1., 1.],
#        [1., 1., 1., 1., 0., 1., 1., 1., 1., 1.],
#        [1., 1., 1., 1., 1., 0., 1., 1., 1., 1.],
#        [1., 1., 1., 1., 1., 1., 0., 1., 1., 1.],
#        [1., 1., 1., 1., 1., 1., 1., 0., 1., 1.],
#        [1., 1., 1., 1., 1., 1., 1., 1., 0., 1.],
#        [1., 1., 1., 1., 1., 1., 1., 1., 1., 0.]])

In [10]:
# Use this cell for your code
D = np.ones((10, 10)) - np.eye(10)
D

array([[0., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 0., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 0., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 0., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 0., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 0., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 0., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 0.]])

4. Create the following array (E):

In [11]:
# array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
#        [1., 1., 1., 1., 1., 1., 1., 1., 0., 1.],
#        [1., 1., 1., 1., 1., 1., 1., 0., 1., 1.],
#        [1., 1., 1., 1., 1., 1., 0., 1., 1., 1.],
#        [1., 1., 1., 1., 1., 0., 1., 1., 1., 1.],
#        [1., 1., 1., 1., 0., 1., 1., 1., 1., 1.],
#        [1., 1., 1., 0., 1., 1., 1., 1., 1., 1.],
#        [1., 1., 0., 1., 1., 1., 1., 1., 1., 1.],
#        [1., 0., 1., 1., 1., 1., 1., 1., 1., 1.],
#        [0., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [12]:
# Use this cell for your code
E = np.fliplr(D)
E

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 0., 1., 1.],
       [1., 1., 1., 1., 1., 1., 0., 1., 1., 1.],
       [1., 1., 1., 1., 1., 0., 1., 1., 1., 1.],
       [1., 1., 1., 1., 0., 1., 1., 1., 1., 1.],
       [1., 1., 1., 0., 1., 1., 1., 1., 1., 1.],
       [1., 1., 0., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

5. Call the last two matrices <span style="background-color: #ccfff2">D</span> and <span style="background-color: #ccfff2">E</span>, respectively. Show that the determinant of their product (matrix multiplication) is the same as the product of their determinants. That is calculate both <span style="background-color: #ccfff2">det(DE)</span> and <span style="background-color: #ccfff2">det(D) * det(E)</span>, and show that they are the same. Is it a coincidence? (I think not) The product of the determinants (or the determinant of the product) should be -81.

In [13]:
# Use this cell for your code
det_product = np.linalg.det(D @ E)
product_dets = np.linalg.det(D) * np.linalg.det(E)
print(det_product, product_dets)

-81.0000000000001 -81.0

-- *Use this markdown cell for your written answer* -- <br>
No, it is not a coincidence. det(AB) = det(A)·det(B) is a general property of determinants for any square matrices.

### 1.3 Slicing

Array slicing is a powerful way to extract data from an array. Let's practice array slicing with the following exercises!

1. Load the [California housing dataset](https://scikit-learn.org/stable/modules/generated/sklearn.datasets.fetch_california_housing.html). The data should be a matrix of shape <span style="background-color: #ccfff2">(20640, 8)</span>, that is 20640 rows and 8 columns. Use the <span style="background-color: #ccfff2">.shape</span> attribute of NumPy arrays to verify this. Here's a [description of the fields](https://scikit-learn.org/stable/datasets/real_world.html#california-housing-dataset).

In [14]:
# Use this cell for your code
from sklearn.datasets import fetch_california_housing

data = fetch_california_housing()
X = data.data
y = data.target
names = data.feature_names
print(X.shape)

(20640, 8)

2. Select rows where the average number of bedrooms <span style="background-color: #ccfff2">(AveBedrms)</span> is higher than 2. The first few row indices should be <span style="background-color: #ccfff2">710,  1023,  1024, ...</span> (zero-indexed). Count these houses - how many rows are selected? *[hint: <span style="background-color: #ccfff2">np.where</span>]*

In [15]:
# Use this cell for your code
bedrms = X[:, names.index('AveBedrms')]
idx = np.where(bedrms > 2)[0]
print(idx[:5], len(idx))

[ 710 1023 1024 1030 1102] 235

3. Select the rows where the median house age (i.e. median in each block group) <span style="background-color: #ccfff2">(HouseAge)</span> is between 1 and 3 years (inclusive). There should be **124** of these.

In [16]:
# Use this cell for your code
age = X[:, names.index('HouseAge')]
mask = (age >= 1) & (age <= 3)
print(mask.sum())

124

4. Find the mean of the block group population <span style="background-color: #ccfff2">(Population)</span> for homes whose median value is more than 25000 USD (the target variable). It should be around **1425.68**.

In [17]:
# Use this cell for your code
pop = X[:, names.index('Population')]
mask = y > 0.25   # target is in units of $100,000
print(pop[mask].mean())

1425.6833737275813

## Exercise 2 | Working with text data

Next, let's look into some text data. We will be looking into Amazon reviews, and the necessary steps to transform a raw dataset into a format more suitable for prediction tasks.

1. Download the automotive 5-core dataset from [here](https://mcauleylab.ucsd.edu/public_datasets/data/amazon_v2/categoryFilesSmall/Automotive_5.json.gz). Next, you can extract the data in <span style="background-color: #ccfff2">JSON</span> format. You can also download one of the bigger ones, if you are feeling ambitious. Open the JSON file. Access the <span style="background-color: #ccfff2">reviewText</span> field, which contains the unstructured review text written by the user.

For instance, the first review reads as follows: 

*'After I wrote the below review, the manufacturer contacted me and explained how to use this.  Instead of the (current) picture on Amazon where the phone is placed vertically, you actually use the stand with the phone placed horizontally. [...]'*

In [18]:
# Use this cell for your code
import gzip, json

reviews = []
with gzip.open('Automotive_5.json.gz', 'rt', encoding='utf-8') as f:
    for line in f:
        reviews.append(json.loads(line))

print(reviews[0]['reviewText'])

After I wrote the below review, the manufacturer contacted me and explained how to use this.  Instead of the (current) picture on Amazon where the phone is placed vertically, you actually use the stand with the phone placed horizontally.  Then the charge / sync cable goes through the hole and you can charge from the side.  When used in landscape position this stand does make more sense so I'm upgrading this review from 2 stars to 4 stars (which I rarely do, but in this case user error) with a star off for lack of documentation.  Manufacturer has said he will include directions and I would also encourage him to update the photos on Amazon with more examples of how this can be used.  The wood quality is indeed good and it's a sturdy little stand.  I'm trying to think of when I'd actually use this stand... perhaps for Facetime chats.  I also think it would be useful for someone in an open office environment if they want to keep their phone on their desk and see alerts / notifications easily.  Hope this updated review helps.

ORIGINAL REVIEW:
I am throwing this stand in the garbage.  While it's crafted of a nice wood, it is not functional as near as I can tell.  It does not come with instructions and as you can see from the product description, even that is confusing since the English is poorly translated Chinese.  The iPhone sits on the stand just fine, but when it's on the stand, there is no way the plug on the bottom  will plug in -- the stand blocks it.  If you turn the iPhone over, the plug is on the top, which just looks strange.  And I'm not at all sure what the hole in the back of the stand is supposed to do.  Also included are four plastic feet, again no instructions, so I affixed them to the bottom of the stand and it began to wobble.

Perhaps someone else will figure out how to work this thing and post a review, but as far as I'm concerned, the out of the box experience was terrible.

Sorry, I cannot recommend.

Sample provided in exchange for an honest review.

2. Next, let's follow some steps to normalize the text data.

When dealing with natural language, it is important to notice that while, for example, the words "Copper" and "copper" are represented by two different strings, they have the same meaning. When applying statistical methods on this data, it is useful to ensure that words with the same meaning are represented by the same string.

* <span style="background-color: #ccfff2">Downcasing</span>: Let's first downcase the contents of the <span style="background-color: #ccfff2">reviewText</span> field.

Now the first review should be:

*'after i wrote the below review, the manufacturer contacted me and explained how to use this.  instead of the (current) picture on amazon where the phone is placed vertically, you actually use the stand with the phone placed horizontally.'*

In [19]:
# Use this cell for your code
reviews[0]['reviewText'].lower()

"after i wrote the below review, the manufacturer contacted me and explained how to use this.  instead of the (current) picture on amazon where the phone is placed vertically, you actually use the stand with the phone placed horizontally.  then the charge / sync cable goes through the hole and you can charge from the side.  when used in landscape position this stand does make more sense so i'm upgrading this review from 2 stars to 4 stars (which i rarely do, but in this case user error) with a star off for lack of documentation.  manufacturer has said he will include directions and i would also encourage him to update the photos on amazon with more examples of how this can be used.  the wood quality is indeed good and it's a sturdy little stand.  i'm trying to think of when i'd actually use this stand... perhaps for facetime chats.  i also think it would be useful for someone in an open office environment if they want to keep their phone on their desk and see alerts / notifications easily.  hope this updated review helps.\n\noriginal review:\ni am throwing this stand in the garbage.  while it's crafted of a nice wood, it is not functional as near as i can tell.  it does not come with instructions and as you can see from the product description, even that is confusing since the english is poorly translated chinese.  the iphone sits on the stand just fine, but when it's on the stand, there is no way the plug on the bottom  will plug in -- the stand blocks it.  if you turn the iphone over, the plug is on the top, which just looks strange.  and i'm not at all sure what the hole in the back of the stand is supposed to do.  also included are four plastic feet, again no instructions, so i affixed them to the bottom of the stand and it began to wobble.\n\nperhaps someone else will figure out how to work this thing and post a review, but as far as i'm concerned, the out of the box experience was terrible.\n\nsorry, i cannot recommend.\n\nsample provided in exchange for an honest review."

3. Let's continue with punctuation and stop word removal. Stop words are words like "and", "the", etc. They are usually very common words that have little to do with the actual content matter. There's plenty openly available lists of stop words for almost any (natural) language.

* <span style="background-color: #ccfff2">Punctuation and stop-word removal</span>: Let's now remove all punctuation, as well as the stop words. You can find a stop word list for English, e.g. [here](https://gist.github.com/xldrkp/4a3b1a33f10d37bedbe0068f2b4482e8#file-stopwords-en-txt).*(use the link to download a txt of english stopwords)* Save the stopwords in the file as "stopwords-en.txt".

First review at this point reads as: 

*'wrote review manufacturer contacted explained current picture amazon phone vertically stand phone horizontally'*

In [20]:
# Use this cell for your code
import string

with open('stopwords-en.txt') as f:
    stopwords = set(line.strip() for line in f)

def clean(text):
    text = text.lower()
    text = text.translate(str.maketrans('', '', string.punctuation))
    tokens = text.split()
    tokens = [t for t in tokens if t not in stopwords]
    return ' '.join(tokens)

print(clean(reviews[0]['reviewText']))

wrote review manufacturer contacted explained use instead current picture amazon phone placed vertically actually use stand phone placed horizontally charge sync cable goes hole charge used landscape position stand does make sense im upgrading review 2 stars 4 stars rarely case user error star lack documentation manufacturer said include directions encourage update photos amazon examples used wood quality good sturdy little stand im trying think id actually use stand facetime chats think useful open office environment want phone desk alerts notifications easily hope updated review helps original review throwing stand garbage crafted nice wood functional near tell does come instructions product description confusing english poorly translated chinese iphone sits stand just fine stand way plug plug stand blocks turn iphone plug just looks strange im sure hole stand supposed included plastic feet instructions affixed stand began wobble figure work thing post review far im concerned box experience terrible sorry recommend sample provided exchange honest review

4. Let's continue with stemming. For example, while the words "swims" and "swim" are different strings, they both refer to swimming. [Stemming](https://en.wikipedia.org/wiki/Stemming) refers to the process of mapping words from their inflected form to their base form, for instance: swims -> swim.

* <span style="background-color: #ccfff2">Stemming</span>: Apply a stemmer on the paragraphs, so that inflected forms are mapped to the base form. For example, for Python the popular natural language toolkit [nltk](http://www.nltk.org/howto/stem.html) has an easy to use stemmer. In case you are using R, you can try the [Snowball stemmer](https://www.rdocumentation.org/packages/corpus/versions/0.10.2/topics/stem_snowball). You can find out how to install nltk from [here](https://www.nltk.org/install.html). It will take a while to run! So, grab a coffee and wait :D

Finally, after stemming: 

*'wrote review manufactur contact explain current pictur amazon phone vertic stand phone horizont'*

In [21]:
# Use this cell for your code
from nltk.stem import PorterStemmer

stemmer = PorterStemmer()

def stem_text(text):
    return ' '.join(stemmer.stem(w) for w in text.split())

print(stem_text(clean(reviews[0]['reviewText'])))

wrote review manufactur contact explain use instead current pictur amazon phone place vertic actual use stand phone place horizont charg sync cabl goe hole charg use landscap posit stand doe make sens im upgrad review 2 star 4 star rare case user error star lack document manufactur said includ direct encourag updat photo amazon exampl use wood qualiti good sturdi littl stand im tri think id actual use stand facetim chat think use open offic environ want phone desk alert notif easili hope updat review help origin review throw stand garbag craft nice wood function near tell doe come instruct product descript confus english poorli translat chines iphon sit stand just fine stand way plug plug stand block turn iphon plug just look strang im sure hole stand suppos includ plastic feet instruct affix stand began wobbl figur work thing post review far im concern box experi terribl sorri recommend sampl provid exchang honest review

5. Finally, filter the data by selecting reviews where the field <span style="background-color: #ccfff2">overall</span> is 4 or 5, and store the review texts in a file named <span style="background-color: #ccfff2">pos.txt</span>. Similarly, select reviews with rating 1 or 2 and store them in a file named <span style="background-color: #ccfff2">neg.txt</span>. Ignore the reviews with overall rating 3. Each line in the two files should contain exactly one preprocessed review text without the rating.

In [22]:
# Use this cell for your code
def preprocess(text):
    return stem_text(clean(text))

with open('pos.txt', 'w', encoding='utf-8') as pos_f, \
     open('neg.txt', 'w', encoding='utf-8') as neg_f:
    for r in reviews:
        rating = r.get('overall')
        text = preprocess(r.get('reviewText', ''))
        if rating in (4, 5):
            pos_f.write(text + '\n')
        elif rating in (1, 2):
            neg_f.write(text + '\n')

## Exercise 3 | SQL basics

Next, let's take a refresher on the basics of SQL. In this exercise, you will be working on the simplified Northwind 2000 SQLite database. You can download the database from Kaggle [here](https://courses.mooc.fi/api/v0/files/course/f92ffc32-2dd4-421d-87f3-c48800422cc5/files/VEKX2bxGCDGyojG902gmYZTXCnrAQw.zip).

To test your SQL queries and complete the exercise, you can download and install SQLite if you don't yet have it installed.

Please write SQL queries for the tasks on the simplified Northwind 2000 SQLite database.

1. List the first name, last name, and hire date of all employees hired after January 1st, 1994.

2. Count how many orders each customer has placed.

3. Find the names of all customers who have ordered the product "Chai".

4. Find all orders that have been placed but not yet shipped.

5. Find the customer who has placed the most orders.

Setting up the database and connecting to it:

In [23]:
import sqlite3
import pandas as pd
from pathlib import Path

DB = Path("northwind2000-simplified.sqlite")
assert DB.exists(), f"Database not found at {DB.resolve()}"

conn = sqlite3.connect(DB)

def q(sql):
    """Run a SQL query and return the result as a DataFrame."""
    return pd.read_sql_query(sql, conn)

# Print the schema so you can confirm the table and column names.
for name, sql in conn.execute(
    "SELECT name, sql FROM sqlite_master WHERE type='table' ORDER BY name"
):
    print(sql, "\n")

CREATE TABLE [Categories]
(      [CategoryID] INTEGER PRIMARY KEY AUTOINCREMENT,
       [CategoryName] TEXT,
       [Description] TEXT)

CREATE TABLE [Customers]
(      [CustomerID] TEXT,
       [CompanyName] TEXT,
       [ContactName] TEXT,
       [ContactTitle] TEXT,
       [Address] TEXT,
       [City] TEXT,
       [Region] TEXT,
       [PostalCode] TEXT,
       [Country] TEXT,
       [Phone] TEXT,
       [Fax] TEXT,
       PRIMARY KEY (`CustomerID`)
)

CREATE TABLE [Employees]
(      [EmployeeID] INTEGER PRIMARY KEY AUTOINCREMENT,
       [LastName] TEXT,
       [FirstName] TEXT,
       [Title] TEXT,
       [TitleOfCourtesy] TEXT,
       [BirthDate] DATE,
       [HireDate] DATE,
       [Address] TEXT,
       [City] TEXT,
       [Region] TEXT,
       [PostalCode] TEXT,
       [Country] TEXT,
       [HomePhone] TEXT,
       [Extension] TEXT,
       [ReportsTo] INTEGER,
	   FOREIGN KEY ([ReportsTo]) REFERENCES [Employees] ([EmployeeID])
		ON DELETE NO ACTION ON UPDATE NO ACTION
)

CREATE TABLE "OrderDetails"(
   [OrderID]INTEGER NOT NULL,
   [ProductID]INTEGER NOT NULL,
   [UnitPrice]NUMERIC NOT NULL DEFAULT 0,
   [Quantity]INTEGER NOT NULL DEFAULT 1,
   [Discount]REAL NOT NULL DEFAULT 0,
    PRIMARY KEY ("OrderID","ProductID"),
    CHECK ([Discount]>=(0) AND [Discount]<=(1)),
    CHECK ([Quantity]>(0)),
    CHECK ([UnitPrice]>=(0)),
	FOREIGN KEY ([OrderID]) REFERENCES [Orders] ([OrderID])
		ON DELETE NO ACTION ON UPDATE NO ACTION,
	FOREIGN KEY ([ProductID]) REFERENCES [Products] ([ProductID])
		ON DELETE NO ACTION ON UPDATE NO ACTION
)

CREATE TABLE [Orders](
   [OrderID]INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
   [CustomerID]TEXT,
   [EmployeeID]INTEGER,
   [OrderDate]DATETIME,
   [RequiredDate]DATETIME,
   [ShippedDate]DATETIME,
   "ShipperID"INTEGER,
   [Freight]NUMERIC DEFAULT 0,
   FOREIGN KEY ([EmployeeID]) REFERENCES [Employees] ([EmployeeID])
		ON DELETE NO ACTION ON UPDATE NO ACTION,
	FOREIGN KEY ([CustomerID]) REFERENCES [Customers] ([CustomerID])
		ON DELETE NO ACTION ON UPDATE NO ACTION,
	FOREIGN KEY ("ShipperID") REFERENCES [Shippers] ([ShipperID])
		ON DELETE NO ACTION ON UPDATE NO ACTION
)

CREATE TABLE [Products](
   [ProductID]INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
   [ProductName]TEXT NOT NULL,
   [SupplierID]INTEGER,
   [CategoryID]INTEGER,
   [QuantityPerUnit]TEXT,
   [UnitPrice]NUMERIC DEFAULT 0,
   [UnitsInStock]INTEGER DEFAULT 0,
   [UnitsOnOrder]INTEGER DEFAULT 0,
   [ReorderLevel]INTEGER DEFAULT 0,
   [Discontinued]TEXT NOT NULL DEFAULT '0',
    CHECK ([UnitPrice]>=(0)),
    CHECK ([ReorderLevel]>=(0)),
    CHECK ([UnitsInStock]>=(0)),
    CHECK ([UnitsOnOrder]>=(0)),
	FOREIGN KEY ([CategoryID]) REFERENCES [Categories] ([CategoryID])
		ON DELETE NO ACTION ON UPDATE NO ACTION,
	FOREIGN KEY ([SupplierID]) REFERENCES [Suppliers] ([SupplierID])
		ON DELETE NO ACTION ON UPDATE NO ACTION
)

CREATE TABLE [Shippers](
   [ShipperID]INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
   [CompanyName]TEXT NOT NULL,
   [Phone]TEXT
)

CREATE TABLE [Suppliers](
   [SupplierID]INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
   [CompanyName]TEXT NOT NULL,
   [ContactName]TEXT,
   [ContactTitle]TEXT,
   [Address]TEXT,
   [City]TEXT,
   [Region]TEXT,
   [PostalCode]TEXT,
   [Country]TEXT,
   [Phone]TEXT,
   [Fax]TEXT)

CREATE TABLE sqlite_sequence(name,seq)

Viewing table names:

In [24]:
print([r[0] for r in conn.execute(
    "SELECT name FROM sqlite_master WHERE type='table' ORDER BY name"
)])

['Categories', 'Customers', 'Employees', 'OrderDetails', 'Orders', 'Products', 'Shippers', 'Suppliers', 'sqlite_sequence']

### Exercise 3.1

In [25]:
q("""
SELECT FirstName, LastName, HireDate
FROM Employees
WHERE HireDate > '1994-01-01'
ORDER BY HireDate;
""")

  FirstName   LastName    HireDate
0    Robert       King  1994-01-02
1     Laura   Callahan  1994-03-05
2      Anne  Dodsworth  1994-11-15

### Exercise 3.2

In [26]:
q("""
SELECT c.CustomerID,
       c.CompanyName,
       COUNT(o.OrderID) AS OrderCount
FROM Customers AS c
LEFT JOIN Orders AS o ON o.CustomerID = c.CustomerID
GROUP BY c.CustomerID, c.CompanyName
ORDER BY OrderCount DESC, c.CompanyName;
""")

   CustomerID                           CompanyName  OrderCount
0       SAVEA                    Save-a-lot Markets          31
1       ERNSH                          Ernst Handel          30
2       QUICK                            QUICK-Stop          28
3       FOLKO                        Folk och fä HB          19
4       HUNGO          Hungry Owl All-Night Grocers          19
..        ...                                   ...         ...
86      GROSR                  GROSELLA-Restaurante           2
87      LAZYK                  Lazy K Kountry Store           2
88      CENTC            Centro comercial Moctezuma           1
89      FISSA  FISSA Fabrica Inter. Salchichas S.A.           0
90      PARIS                     Paris spécialités           0

[91 rows x 3 columns]

Exercise 3.3

In [27]:
q("""
SELECT DISTINCT c.CompanyName
FROM Customers AS c
JOIN Orders AS o        ON o.CustomerID = c.CustomerID
JOIN OrderDetails AS od ON od.OrderID = o.OrderID
JOIN Products AS p      ON p.ProductID = od.ProductID
WHERE p.ProductName = 'Chai'
ORDER BY c.CompanyName;
""")

                     CompanyName
0             Berglunds snabbköp
1       Blondesddsl père et fils
2          Bottom-Dollar Markets
3              Chop-suey Chinese
4              Die Wandernde Kuh
5                Du monde entier
6             Eastern Connection
7            Godos Cocina Típica
8        Great Lakes Food Market
9               HILARION-Abastos
10  Hungry Owl All-Night Grocers
11              LINO-Delicateses
12              La maison d'Asie
13           Lehmanns Marktstand
14      Lonesome Pine Restaurant
15                Mère Paillarde
16                   North/South
17     Pericles Comidas clásicas
18        Princesa Isabel Vinhos
19                    QUICK-Stop
20                 Queen Cozinha
21    Rattlesnake Canyon Grocery
22            Save-a-lot Markets
23            Seven Seas Imports
24              Suprêmes délices
25               The Cracker Box
26           Tortuga Restaurante
27                Wartian Herkku
28        Wellington Importadora
29                   Wilman Kala
30                Wolski  Zajazd

### Exercise 3.4

In [28]:
q("""
SELECT OrderID, CustomerID, OrderDate, RequiredDate
FROM Orders
WHERE ShippedDate IS NULL
ORDER BY OrderDate;
""")

    OrderID CustomerID                OrderDate             RequiredDate
0     11008      ERNSH  1998-04-08 00:00:00.000  1998-05-06 00:00:00.000
1     11019      RANCH  1998-04-13 00:00:00.000  1998-05-11 00:00:00.000
2     11039      LINOD  1998-04-21 00:00:00.000  1998-05-19 00:00:00.000
3     11040      GREAL  1998-04-22 00:00:00.000  1998-05-20 00:00:00.000
4     11045      BOTTM  1998-04-23 00:00:00.000  1998-05-21 00:00:00.000
5     11051      LAMAI  1998-04-27 00:00:00.000  1998-05-25 00:00:00.000
6     11054      CACTU  1998-04-28 00:00:00.000  1998-05-26 00:00:00.000
7     11058      BLAUS  1998-04-29 00:00:00.000  1998-05-27 00:00:00.000
8     11059      RICAR  1998-04-29 00:00:00.000  1998-06-10 00:00:00.000
9     11061      GREAL  1998-04-30 00:00:00.000  1998-06-11 00:00:00.000
10    11062      REGGC  1998-04-30 00:00:00.000  1998-05-28 00:00:00.000
11    11065      LILAS  1998-05-01 00:00:00.000  1998-05-29 00:00:00.000
12    11068      QUEEN  1998-05-04 00:00:00.000  1998-06-01 00:00:00.000
13    11070      LEHMS  1998-05-05 00:00:00.000  1998-06-02 00:00:00.000
14    11071      LILAS  1998-05-05 00:00:00.000  1998-06-02 00:00:00.000
15    11072      ERNSH  1998-05-05 00:00:00.000  1998-06-02 00:00:00.000
16    11073      PERIC  1998-05-05 00:00:00.000  1998-06-02 00:00:00.000
17    11074      SIMOB  1998-05-06 00:00:00.000  1998-06-03 00:00:00.000
18    11075      RICSU  1998-05-06 00:00:00.000  1998-06-03 00:00:00.000
19    11076      BONAP  1998-05-06 00:00:00.000  1998-06-03 00:00:00.000
20    11077      RATTC  1998-05-06 00:00:00.000  1998-06-03 00:00:00.000

### Exercise 3.5

In [29]:
q("""
SELECT c.CustomerID,
       c.CompanyName,
       COUNT(o.OrderID) AS OrderCount
FROM Customers AS c
JOIN Orders AS o ON o.CustomerID = c.CustomerID
GROUP BY c.CustomerID, c.CompanyName
ORDER BY OrderCount DESC
LIMIT 1;
""")

  CustomerID         CompanyName  OrderCount
0      SAVEA  Save-a-lot Markets          31

Closing the database connection:

In [30]:
conn.close()

**Remember to submit your solutions. You can return this Jupyter notebook (.ipynb) or .py, .R, etc depending on your programming preferences. Remember to also submit your SQL queries. No need to submit the text files for the programming exercises.**